### ISSUE TITLE
Ports für NodeRed und MQTT dürfen nicht durch den ioBroker Container blockiert werden

### ISSUE THREAD

**Issue by schoebelh** [mgutt/unraid-docker-templates#1]
Hallo,
im von Dir bereitgestellten Definitionsfile für den iobroker Docker Container auf unraid leitest Du die Ports 1880 (NodeRed) und 1883 (MQTT) auf diesen (iobroker-) Container - obwohl beide Dienste ja von anderen Containern bereitgestellt werden. Dies führt bei mir u.a. bei Updates immer dazu, dass der Container nicht startet - da die beiden Ports ja bereits durch andere Container belegt sind.
Was ist denn der Grund für die Reservierung dieser beiden Ports?
Gruß...
...Hagen

**Comment by mgutt** [comment]
ioBroker kann auch als MQTT Broker fungieren und muss dann auf 1883 lauschen:
https://www.iobroker.net/docu/index-378.htm?page_id=3790&lang=de#IoBroker_working_as_MQTT-client

Du solltest das Netzwerk des ioBroker Container oder das des anderen auf br0 stellen und eine feste IP vergeben, die nicht dem Server entspricht. Dann können mehrere Container auf den selben Ports lauschen.

Alternativ könntest du als Host Port auch einfach einen anderen hinterlegen. Bei einem Update sollte diese Anpassung eigentlich nicht geändert werden.

**Comment by schoebelh** [comment]
Ich hab jetzt tatsächlich "Fake"-Ports hinterlegt - so passt das erstmal. Vorher hatte ich die Ports aus dem Template gelöscht - was dann eben bei einem Update zu Problemen führte (die tauchten dann wieder auf).
